#!/usr/bin/env node

var $ = require('./config');
var proxy = require("anyproxy");

!proxy.isRootCAFileExists() && proxy.generateRootCA(function(error, keyPath, crtPath){

    if(error){
        console.log("error:", error);
    }else{
        console.log("keyPath:", keyPath);
        console.log("crtPath:", crtPath);
    }
                                
});

var options = {
    type          : $.proxy.type,
    hostname      : $.proxy.host,
    rule          : require("./rule"),
    port          : 8001,
    webPort       : 8002,  
    socketPort    : 8003,  
    interceptHttps: true
};

new proxy.proxyServer(options);