#!/bin/bash

start(){
	nohup ./anyproxy_server -i &
	if [ $? -eq 0 ];then
		echo "Starting anyproxy: [  OK  ]"
	else
		echo "Starting anyproxy: [  Faild  ]"
	fi
}

stop(){
	pid=`ps -ef | grep "anyproxy_server" | grep -v grep | awk '{print $2}'`
	kill -QUIT $pid
	if [ $? -eq 0 ];then
		echo "Stopping anyproxy: [  OK  ]"
	else
		echo "Stopping anyproxy: [  Faild  ]"
	fi
}

case $1 in
	"start")
		start
	;;
	"stop")
		stop
	;;
	"restart")
		stop
		start     
	;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 2
esac
